### PR TITLE
fix: set time for GTK context menu

### LINKED ISSUE #9658: [v2] context menu disappears on button release
### Describe the bug

When I popup a context menu using JS API `@tauri-apps/api/menu`, the menu shows normally, but is closed as soon as the right mouse button is released.
This makes it quite unusable.

### Reproduction

Svelte minimal example:
```svelte
<script lang="ts">
  import { Menu, MenuItem } from '@tauri-apps/api/menu';

  async function contextMenu() {
    const menu = await Menu.new();

    menu.append(
      await MenuItem.new({
        text: 'Open',
        action: async () => {}
      })
    );

    await menu.popup();
  }
</script>

<div>
  <p on:contextmenu|preventDefault={contextMenu}>test</p>
</div>
```

### Expected behavior

The context menu should behave just like with any other toolkit.

### Full `tauri info` output

```text
[✔] Environment
    - OS: Ubuntu 23.10.0 X64
    ✔ webkit2gtk-4.1: 2.44.0
    ✔ rsvg2: 2.54.7
    ✔ rustc: 1.75.0 (82e1608df 2023-12-21)
    ✔ cargo: 1.75.0 (1d8b05cdd 2023-11-20)
    ✔ rustup: 1.27.0 (bbb9276d2 2024-03-08)
    ✔ Rust toolchain: stable-x86_64-unknown-linux-gnu (environment override by RUSTUP_TOOLCHAIN)
    - node: 21.5.0
    - pnpm: 8.15.5
    - npm: 10.2.4

[-] Packages
    - tauri [RUST]: 2.0.0-beta.17 (no manifest)
    - tauri-build [RUST]: 2.0.0-beta.13 (no manifest)
    - wry [RUST]: 0.39.3 (no manifest)
    - tao [RUST]: 0.27.1 (no manifest)
    - tauri-cli [RUST]: 2.0.0-beta.15
    - @tauri-apps/api [NPM]: 2.0.0-beta.11
    - @tauri-apps/cli [NPM]: 2.0.0-beta.15

[-] App
    - build-type: build
    - CSP: unset
    - frontendDist: ../build
    - devUrl: http://localhost:5173/
    - framework: Svelte
    - bundler: Vite
```

### Stack trace

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by rtbo**
This fixes tauri-apps/tauri#9658.
I noticed somehow that setting the `time` field of the GDK event prevents GTK from closing the menu on right click release.

### CODE REVIEW

**Comment by rtbo** [comment]
Clippy errors are unrelated

**Comment by pewsheen** [comment]
Cool, It works!

How did you find out it was the `time` field?

**Comment by pewsheen** [comment]
By the way, you'll need to [sign the commit](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits) and [add a change log file](https://github.com/tauri-apps/muda/blob/8ad2b8378fd4261805dd0823672084b9694bbc5b/.changes/readme.md) so that it can be merged

**Comment by rtbo** [comment]
> How did you find out it was the time field?

I made a minimal GTK app in C that mimics muda menu creation.
I could reproduce the issue easily, and checked that passing the original right click event to `popup_at_rect` makes it behave normally.
Then I played with the fields of the synthetized event to find out which one triggers the expected behavior.

**Pull request merged**
